/**
 * COACH-DATI-EN — the English texts of the gym (27/09/2026).
 * Keyed by the Italian text in coach-dati.js: coach.js swaps them when the
 * gym is opened in English (?lang=en). On-screen labels stay in Italian, with
 * the meaning in brackets, because that is what people see on the page.
 */
window.COACH_EN = {
  // exercise titles
  "Orientarsi nella home": "Finding your way on the home page",
  "La pagina del MAM": "The MAM page",
  "Cercare una partita": "Finding a match",
  "Sfogliare l'archivio": "Browsing the archive",
  "Cercare un giocatore": "Finding a player",
  "Solo i gol, solo gli assist": "Only goals, only assists",
  "Cercare una frase della telecronaca": "Finding a commentary line",
  "Guardare una partita": "Watching a match",
  "La barra della partita": "The match bar",
  "Le azioni della partita": "The plays of the match",
  "Scegliere le azioni e usarle": "Selecting plays and using them",
  "Mandare una macchia in regia": "Sending a clip to the control room",
  "Le zone dell'Editing": "The areas of the Editor",
  "Aprire una partita": "Opening a match",
  "Segnare inizio e fine": "Marking in and out",
  "Mettere il pezzo nel montaggio": "Putting the clip in the edit",
  "Aggiungere altri pezzi": "Adding more clips",
  "Guardare il montaggio": "Watching your edit",
  "Togliere un pezzo (e annullare)": "Removing a clip (and undo)",
  "Tagliare un pezzo in due": "Cutting a clip in two",
  "Accorciare un pezzo": "Shortening a clip",
  "Scrivere un titolo": "Writing a title",
  "Orizzontale o verticale": "Landscape or vertical",
  "Esportare il video": "Exporting the video",
  "Ritrovare un montaggio": "Finding an edit again",
  "Tutti i tasti": "All the shortcuts",
  "Il catalogo delle grafiche": "The graphics catalogue",
  "Preparare le formazioni (Premium con foto)": "Preparing the line-ups (Premium with photos)",
  "I risultati della giornata": "The day's results",
  "Correggere una grafica in scaletta": "Fixing a graphic in the rundown",
  "Trovare un'immagine nel Magazzino": "Finding an image in the Magazzino",
  "Prendere la formazione per la telecronaca": "Getting the line-up for commentary",
  "Fare una copertina": "Making a cover",
  "Fare un post per i social": "Making a social post",
  "La pagina del MAM Como 1907": "The MAM Como 1907 page",
  "Stagione, squadra, tipo": "Season, team, type",
  "Cercare una persona": "Finding a person",
  "La scheda partita": "The match card",
  "Chi ha girato, dove, quando": "Who shot it, where, when",
  "Guardare un video, anche i .mov": "Watching a video, .mov too",
  "Scegliere e salvare in raccolta": "Picking and saving to a collection",
  "Montare: Editing e Premiere": "Editing: Editor and Premiere",
  "Cercare con i volti": "Searching by face",

  // steps
  "Clicca Volti, a destra nel campo di ricerca": "Click Volti (faces), on the right of the search box",
  "Clicca una faccia": "Click a face",
  "Diventa un gettone, insieme a «Si vede»: i video dove c'è il suo volto, non solo il suo nome.": "It becomes a token, together with «Si vede» (seen): the videos where their face appears, not just their name.",
  "Spunta solo primi piani": "Tick solo primi piani (close-ups only)",
  "Clicca Mostra i video": "Click Mostra i video (show the videos)",
  "Sotto ogni video, le faccine di chi si vede: bordo oro è primo piano": "Under each video, the faces of who appears: a gold ring means close-up",
  "Le stagioni: una locandina per stagione": "Seasons: one poster per season",
  "Clicca una stagione": "Click a season",
  "Le collezioni della stagione scelta": "The collections of the season you picked",
  "Sotto, i servizi: dal più recente, con la data delle riprese": "Below, the shoots: newest first, by shooting date",
  "Nella riga Sfoglia scegli la squadra: Prima squadra": "In the Sfoglia (browse) row pick the team: Prima squadra (first team)",
  "Clicca Tutti i tipi: si apre la tendina": "Click Tutti i tipi (all types): the list opens",
  "Clicca Intervista": "Click Intervista (interview)",
  "Il numero accanto conta i servizi di quel tipo.": "The number next to it counts the shoots of that type.",
  "Clicca Lista: gli stessi servizi in righe": "Click Lista (list): the same shoots as rows",
  "Scrivi: douvikas": "Type: douvikas",
  "Nella sua scheda clicca la tessera Intervista": "On his card click the Intervista (interview) tile",
  "La scheda dice cosa c'è di lui nel materiale del club: video, foto, tipi, stagioni, partite.": "The card shows what the club footage has of him: videos, photos, types, seasons, matches.",
  "Clicca Cerca: le sue interviste": "Click Cerca (search): his interviews",
  "Scrivi: napoli": "Type: napoli",
  "Sotto Partite clicca Napoli–Como": "Under Partite (matches) click Napoli–Como",
  "La scheda: risultato, gol, e cosa ha girato il club quel giorno": "The card: score, goals, and what the club shot that day",
  "Momenti: clicca Riscaldamento": "Momenti (moments): click Riscaldamento (warm-up)",
  "Scrivi: juventus": "Type: juventus",
  "Premi Invio": "Press Enter",
  "Clicca Filtri": "Click Filtri (filters)",
  "Chi ha girato: spunta un nome": "Chi ha girato (who shot it): tick a name",
  "Ogni spunta diventa un gettone nel campo di ricerca.": "Each tick becomes a token in the search box.",
  "Scrivi: drone": "Type: drone",
  "Clicca il nome di un file: si apre": "Click a file name: it opens",
  "Passando col mouse sulla miniatura scorre il provino.": "Moving the mouse over the thumbnail scrubs through the contact sheet.",
  "Copia percorso: il file sulla NAS, da aprire sul Mac": "Copia percorso (copy path): the file on the NAS, to open on your Mac",
  "Clicca il + su un file": "Click the + on a file",
  "In basso: Salva in raccolta": "At the bottom: Salva in raccolta (save to collection)",
  "Scrivi un nome e clicca Salva": "Type a name and click Salva (save)",
  "Clicca una raccolta": "Click a collection",
  "Premiere (XML): gli originali della NAS già collegati": "Premiere (XML): the NAS originals already linked",
  "Monta tutta: una sequenza nell'Editing 1907": "Monta tutta (edit all): a sequence in Editing 1907",
  "Le tessere sono gli strumenti. In alto a sinistra la Guida": "The tiles are the tools. Top left: the Guide",
  "LIVE: grafiche in onda, redazione, regia, telecronaca": "LIVE: on-air graphics, newsroom, control room, commentary",
  "MAM e Magazzino: archivio, raccolte, montaggio, immagini": "MAM & Magazzino: archive, collections, editing, images",
  "La barra in alto è uguale in tutte le pagine: clicca MAM": "The top bar is the same on every page: click MAM",
  "Qui scrivi cosa cerchi": "Type what you're looking for here",
  "Questo riquadro dice quante partite sono pronte": "This box shows how many matches are ready",
  "Sfoglia: per guardare senza cercare": "Sfoglia (browse): look without searching",
  "Sotto, tutte le partite: la più recente in cima": "Below, all the matches: newest at the top",
  "Clicca nel campo di ricerca": "Click in the search box",
  "Scrivi: como": "Type: como",
  "Nel menu, sotto Squadre, clicca Como": "In the menu, under Squadre (teams), click Como",
  "Clicca la squadra nel menu: non premere Invio.": "Click the team in the menu: don't press Enter.",
  "Ora scrivi: genoa": "Now type: genoa",
  "Clicca Genoa nel menu": "Click Genoa in the menu",
  "Ecco la partita fra le due squadre": "Here is the match between the two teams",
  "Apri il menu delle competizioni": "Open the competitions menu",
  "Scegli Serie A": "Pick Serie A",
  "Clicca Anteprime: le partite come copertine": "Click Anteprime: matches as cover cards",
  "Clicca Lista per tornare all'elenco": "Click Lista to go back to the list",
  "Scrivi: nico paz": "Type: nico paz",
  "Nel menu clicca Nico Paz (Como)": "In the menu click Nico Paz (Como)",
  "Clicca il giocatore nel menu: così il MAM sa che è proprio lui.": "Click the player in the menu: that way the MAM knows it's really him.",
  "Ecco la sua scheda: i suoi numeri nell'archivio": "Here's his card: his numbers in the archive",
  "Clicca una sua azione: la partita parte da lì": "Click one of his plays: the match starts there",
  "Clicca la casella Gol: restano solo i gol": "Click the Gol box: only goals remain",
  "Nella scheda di Nico Paz, il primo numero.": "On Nico Paz's card, the first number.",
  "Apri Filtri: competizione e stagione": "Open Filtri (filters): competition and season",
  "Scrivi la frase tra virgolette: \"che gol\"": "Type the phrase in quotes: \"che gol\"",
  "Le virgolette dicono al MAM che è una frase, non un nome.": "The quotes tell the MAM it's a phrase, not a name.",
  "Premi Invio": "Press Enter",
  "Clicca un momento: la partita parte lì": "Click a moment: the match plays from there",
  "Prima apri una partita. Scrivi: nico paz": "First open a match. Type: nico paz",
  "Clicca una sua azione: si apre la partita": "Click one of his plays: the match opens",
  "Premi Spazio: parte": "Press Space: it plays",
  "Premi J: indietro di 10 secondi": "Press J: back 10 seconds",
  "Premi L: avanti (ancora L: più veloce)": "Press L: forward (L again: faster)",
  "Premi K: ferma": "Press K: stop",
  "Freccia destra: un fotogramma avanti": "Right arrow: one frame forward",
  "Questa è la barra: sopra la casa, sotto gli ospiti": "This is the bar: home team above, away team below",
  "Clicca un pallone: il video salta al gol": "Click a ball: the video jumps to the goal",
  "Il pallone è un gol. Passaci sopra per vedere l'azione.": "The ball is a goal. Hover over it to see the play.",
  "Nel campo a destra scrivi un nome: paz": "In the box on the right type a name: paz",
  "Spunta un'azione: la scegli per il montaggio": "Tick a play: you pick it for editing",
  "Clicca il + su un'azione": "Click the + on a play",
  "Clicca il + su un'altra azione": "Click the + on another play",
  "Salva in raccolta: dagli un nome": "Salva in raccolta (save to collection): give it a name",
  "In palestra la raccolta resta nell'ambiente di prova.": "In the gym the collection stays in the test environment.",
  "Si parla dei pali di Nico Paz? Scrivi: nico paz": "Talking about Nico Paz hitting the post? Type: nico paz",
  "Clicca la casella Pali (o Tiri)": "Click the Pali box (woodwork), or Tiri (shots)",
  "Clicca il + sulle azioni da mandare": "Click the + on the plays to send",
  "Nella barra in basso clicca Invia alla regia": "In the bar at the bottom click Invia alla regia (send to control room)",
  "Scegli il vMix": "Pick the vMix",
  "Clicca Invia alla regia: parte un filmato grezzo": "Click Invia alla regia: a rough clip is made",
  "8 secondi prima e 10 dopo ogni azione. In palestra finisce nella scaletta di prova.": "8 seconds before and 10 after each play. In the gym it lands in the test rundown.",
  "Sorgente: la partita da cui prendi i pezzi": "Sorgente (Source): the match you take clips from",
  "Programma: il tuo montaggio": "Programma (Program): your edit",
  "Timeline: i pezzi uno dopo l'altro": "Timeline: the clips one after another",
  "Pannelli: partite (Browser media) e montaggi (Progetto)": "Panels: matches (Browser media) and edits (Progetto)",
  "Clicca Browser media": "Click Browser media",
  "Scrivi il nome della partita: cremonese": "Type the match name: cremonese",
  "Fai due clic sulla partita": "Double-click the match",
  "Clicca sul video e premi Spazio": "Click on the video and press Space",
  "Prima apri una partita: clicca Browser media": "First open a match: click Browser media",
  "Clicca sul video, poi premi I: inizio del pezzo": "Click on the video, then press I: clip start",
  "Guarda l'azione (Spazio) e premi O alla fine": "Watch the play (Space) and press O at the end",
  "Qui leggi inizio, fine e durata": "Here you read in, out and length",
  "Clicca sul video e premi I all'inizio dell'azione": "Click on the video and press I at the start of the play",
  "Premi O alla fine dell'azione": "Press O at the end of the play",
  "Premi la virgola (o INSERISCI) e dai un nome": "Press comma (or INSERISCI) and give it a name",
  "Il pezzo è nella timeline: il montaggio è nato": "The clip is in the timeline: your edit is born",
  "Nella Sorgente vai a un'altra azione e premi I": "In the Source go to another play and press I",
  "Premi O alla fine": "Press O at the end",
  "Premi la virgola: il pezzo va dopo la testina": "Press comma: the clip goes after the playhead",
  "Clicca tutta: vedi tutto il montaggio": "Click tutta (all): see the whole edit",
  "Prima apri un montaggio: clicca Progetto": "First open an edit: click Progetto",
  "Fai due clic su un montaggio": "Double-click an edit",
  "Clicca nella timeline e premi Spazio": "Click in the timeline and press Space",
  "Freccia giù: il pezzo dopo": "Down arrow: next clip",
  "Home: torna all'inizio": "Home: back to the start",
  "Clicca sul righello per spostarti": "Click on the ruler to move",
  "Clicca un pezzo: si illumina": "Click a clip: it lights up",
  "Premi Canc (o Backspace)": "Press Delete (or Backspace)",
  "Premi Cmd + Z: torna com'era": "Press Cmd + Z: it's back",
  "Premi C: prendi la lametta": "Press C: pick up the razor",
  "Clicca un pezzo dove vuoi tagliarlo": "Click a clip where you want to cut it",
  "Premi V: torni alla freccia": "Press V: back to the pointer",
  "Trascina il bordo di un pezzo": "Drag the edge of a clip",
  "Porta il mouse sul bordo: il pezzo si accorcia o si allunga.": "Move the mouse to the edge: the clip gets shorter or longer.",
  "Oppure: testina nel punto giusto e premi Q (taglia l'inizio)": "Or: playhead in the right spot and press Q (trim start)",
  "Clicca nella timeline e premi T": "Click in the timeline and press T",
  "Ti chiede il nome grande, la riga piccola e dove metterlo.": "It asks for the big name, the small line and where to put it.",
  "Il titolo è sul video e sopra i pezzi": "The title is on the video and above the clips",
  "Clicca 9:16: verticale per storie e reel": "Click 9:16: vertical for stories and reels",
  "Clicca 16:9 per tornare orizzontale": "Click 16:9 to go back to landscape",
  "In basso a sinistra apri Esporta": "Bottom left, open Esporta (export)",
  "Clicca Esporta… (o Cmd + M)": "Click Esporta… (or Cmd + M)",
  "A sinistra spunta i formati": "On the left tick the formats",
  "Spunta: metti anche in una raccolta": "Tick: metti anche in una raccolta (also put in a collection)",
  "ESPORTA fa partire il file (in palestra non premerlo)": "ESPORTA starts the file (in the gym, don't press it)",
  "L'esportazione usa il server: in allenamento fermati qui.": "Exporting uses the server: when practising, stop here.",
  "Clicca Progetto, in basso a sinistra": "Click Progetto, bottom left",
  "Due clic su un montaggio per aprirlo": "Double-click an edit to open it",
  "Clicca nella timeline e premi ?": "Click in the timeline and press ?",
  "Ogni anteprima è la grafica vera: passaci sopra": "Every preview is the real graphic: hover over it",
  "Clicca Apri l'editor su Formazioni Premium con foto": "Click Apri l'editor (open editor) on Formazioni Premium con foto",
  "Nel riquadro in alto scegli la competizione": "In the box at the top pick the competition",
  "Scegli il giorno della partita": "Pick the match day",
  "Scegli la partita": "Pick the match",
  "Clicca Prendi le formazioni": "Click Prendi le formazioni (get line-ups)",
  "Controlla gli undici: nomi, numeri, foto": "Check the XIs: names, numbers, photos",
  "Un nome sbagliato si corregge nella sua casella. Senza foto c'è la versione solo maglie.": "A wrong name is fixed in its box. Without photos there's the kits-only version.",
  "Clicca Anteprima e guardala": "Click Anteprima (preview) and watch it",
  "Clicca Invia alla regia": "Click Invia alla regia (send to control room)",
  "In palestra arriva nella scaletta di prova, non in onda.": "In the gym it lands in the test rundown, not on air.",
  "Scegli la competizione": "Pick the competition",
  "Scegli i giorni: dal": "Pick the dates: dal (from)",
  "…al": "…al (to)",
  "Clicca Carica": "Click Carica (load)",
  "Clicca Anteprima": "Click Anteprima (preview)",
  "Da dove: scegli il canale": "Da dove (from where): pick the channel",
  "Chi corregge: scegli il tuo nome": "Chi corregge (who): pick your name",
  "Clicca la grafica nella scaletta": "Click the graphic in the rundown",
  "Correggi i campi e clicca Anteprima": "Fix the fields and click Anteprima",
  "Dove va: Al suo posto": "Dove va (where it goes): Al suo posto (in its place)",
  "Clicca Nico Paz nel menu": "Click Nico Paz in the menu",
  "Clicca una foto per vederla grande": "Click a photo to see it big",
  "Scegli il giorno": "Pick the day",
  "Clicca una partita": "Click a match",
  "Clicca Prendi la formazione": "Click Prendi la formazione (get line-up)",
  "Prendi la penna e disegna sul campo": "Pick up the pen and draw on the pitch",
  "Scegli la partita dal menu in alto": "Pick the match from the menu at the top",
  "Riempie da solo competizione, squadre, data e ora. Si può anche scrivere a mano.": "It fills in competition, teams, date and time. You can also type them by hand.",
  "Controlla i campi a sinistra": "Check the fields on the left",
  "Clicca SELEZIONA su un gruppo di modelli": "Click SELEZIONA (select) on a group of templates",
  "Scarica: la freccia in alto a destra, o lo ZIP per tutti": "Download: the arrow top right, or the ZIP for all",
  "Clicca SELEZIONA su Social media": "Click SELEZIONA on Social media",
  "Il primo gruppo: i formati per il feed e le storie.": "The first group: formats for feed and stories.",
  "Clicca il mirino: sposti la foto nel riquadro": "Click the crosshair: move the photo in the frame",
  "Scarica tutto nello ZIP": "Download everything as a ZIP",

  // interface
  "__ui": {
    "Passo": "Step", "di": "of", "Fatto, avanti →": "Done, next →", "Apri la pagina": "Open the page",
    "Guarda come si fa": "Watch how", "Salta": "Skip", "Torna alla palestra": "Back to the gym",
    "Altri pezzi": "Other exercises", "Chiudi": "Close", "Rifallo": "Do it again", "Fatto": "Done",
    "Pezzo completato:": "Exercise completed:", "punti": "points", "totale": "total",
    "PALESTRA": "GYM",
    "Non vedo ancora il punto giusto su questa pagina:": "I can't see the right spot on this page yet:",
    "prima apri la pagina giusta.": "open the right page first.", "scorri o aspetta che carichi.": "scroll, or wait for it to load.",
    "Hai preso la patente": "You earned the licence"
  }
};
